spring.application.name=StudyCenter
spring.datasource.url=jdbc:postgresql://localhost:5432/study_center
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
spring.main.lazy-initialization=true
spring.flyway.baselineOnMigrate=true
spring.flyway.baselineVersion=1
server.port=9091

ESKIZ_EMAIL= your_email
ESKIZ_PASSWORD=your_password

JWT_LIVE_TIME=86400000
JWT_SECRET_KEY=G9%t7L!n@2#bXq$w8Zr^p3Md&*jQyVzK
