spring.application.name=StudyCenter
spring.datasource.url=jdbc:postgresql://localhost:5432/study_center
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true

TOKEN_LIVE_TIME=1000 * 60 * 60 * 24
TOKEN_SECRET_KEY=LaudateomnesgenteslaudateMagnificatinseculaEtanimamealaudateMagnificatinseculaHappynation,livin'inahappynationAddthistothedependenciesblockinyourbuild.gradlefile.Letmeknowifyouneedfurtherassistance!

server.port=9091
